package:
  name: venusian
  version: 1.0a8

source:
  fn: venusian-1.0a8.tar.gz
  url: https://pypi.python.org/packages/source/v/venusian/venusian-1.0a8.tar.gz
  md5: a1a72166fd7cccf0f30e3305e09ce5cf
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - venusian = venusian:main
    #
    # Would create an entry point called venusian that calls venusian.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - distribute

test:
  # Python imports
  imports:
    - venusian

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pylonsproject.org
  license: BSD-derived

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
