package:
  name: waitress
  version: 0.8.7

source:
  fn: waitress-0.8.7.tar.gz
  url: https://pypi.python.org/packages/source/w/waitress/waitress-0.8.7.tar.gz
  md5: 714f3d458d82a47f12fb168460de8366
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - waitress = waitress:main
    #
    # Would create an entry point called waitress that calls waitress.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - distribute

test:
  # Python imports
  imports:
    - waitress

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/Pylons/waitress
  license: Zope Public License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
