package:
  name: flask-sqlalchemy
  version: 1.0

source:
  fn: Flask-SQLAlchemy-1.0.tar.gz
  url: https://pypi.python.org/packages/source/F/Flask-SQLAlchemy/Flask-SQLAlchemy-1.0.tar.gz
  md5: dca034849ffcbaef7b848e8728d3668f
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - flask-sqlalchemy:main
    #
    # Would call flask-sqlalchemy.main()

  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    # If setuptools is required to run setup.py, add distribute to the build
    # requirements.
    #
    - distribute
    - sqlalchemy
    - flask

  run:
    - python
    - sqlalchemy
    - flask

test:
  # Python imports
  imports:
    - flask_sqlalchemy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.

  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any test requirements here.  For example
    # - nose

about:
  home: https://github.com/mitsuhiko/flask-sqlalchemy

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
