package:
  name: amqp
  version: 1.3.0

source:
  fn: amqp-1.3.0.tar.gz
  url: https://pypi.python.org/packages/source/a/amqp/amqp-1.3.0.tar.gz
  md5: 9e16415611127080a486bfd5a49e7ec9
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - amqp = amqp:main
    #
    # Would create an entry point called amqp that calls amqp.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python

test:
  # Python imports
  imports:
    - amqp

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://github.com/celery/py-amqp
  license: BSD License or GNU Library or Lesser General Public License (LGPL)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
