package:
  name: translationstring
  version: 1.1

source:
  fn: translationstring-1.1.tar.gz
  url: https://pypi.python.org/packages/source/t/translationstring/translationstring-1.1.tar.gz
  md5: 0979b46d8f0f852810c8ec4be5c26cf2
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - translationstring = translationstring:main
    #
    # Would create an entry point called translationstring that calls translationstring.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute

  run:
    - python
    - distribute

test:
  # Python imports
  imports:
    - translationstring

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://pylonsproject.org
  license: BSD-like (http://repoze.org/license.html)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
