package:
  name: pyramid_chameleon
  version: 0.1

source:
  fn: pyramid_chameleon-0.1.tar.gz
  url: https://pypi.python.org/packages/source/p/pyramid_chameleon/pyramid_chameleon-0.1.tar.gz
  md5: 39b1327a9890f382200bbfde943833d7
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - pyramid_chameleon = pyramid_chameleon:main
    #
    # Would create an entry point called pyramid_chameleon that calls pyramid_chameleon.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute
    - pyramid
    - chameleon

  run:
    - python
    - distribute
    - pyramid
    - chameleon

test:
  # Python imports
  imports:
    - pyramid_chameleon

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: https://github.com/Pylons/pyramid_chameleon
  license: BSD-derived (http://www.repoze.org/LICENSE.txt)

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
