package:
  name: kombu
  version: 3.0.0

source:
  fn: kombu-3.0.0.tar.gz
  url: https://pypi.python.org/packages/source/k/kombu/kombu-3.0.0.tar.gz
  md5: 686e19ed87824c49db90baa151eea257
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - kombu = kombu:main
    #
    # Would create an entry point called kombu that calls kombu.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - distribute
    - anyjson
    - amqp

  run:
    - python
    - anyjson
    - amqp

test:
  # Python imports
  imports:
    - kombu

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://kombu.readthedocs.org
  license: BSD License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
